version: '3.8'

services:
  api-docs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    volumes:
      - api-docs-data:/app/.next/cache

volumes:
  api-docs-data:

